"use client"

import * as React from "react"
import { useSession, signOut } from "next-auth/react"
import { usePathname, useRouter } from "next/navigation"
import Link from "next/link"
import { 
  BookOpen, 
  Users, 
  FolderOpen, 
  Settings, 
  LogOut, 
  User,
  FileText,
  BarChart3,
  Upload,
  Calendar
} from "lucide-react"
import {
  Sidebar,
  SidebarContent,
  SidebarGroup,
  SidebarGroupContent,
  SidebarGroupLabel,
  SidebarHeader,
  SidebarFooter,
  SidebarMenu,
  SidebarMenuButton,
  SidebarMenuItem,
  SidebarRail,
} from "@/components/ui/sidebar"
import { Button } from "@/components/ui/button"
import { ThemeToggle } from "@/components/theme-toggle"
import { TeamSwitcher } from "@/components/team-switcher"
import { NavUser } from "@/components/nav-user"

const getNavigationItems = (role: string) => {
  const baseItems = []
  
  // Only show Dashboard for ADMIN and PROGRAM_HEAD
  if (['ADMIN', 'PROGRAM_HEAD'].includes(role)) {
    baseItems.push({
      title: "Dashboard",
      url: "/dashboard",
      icon: BarChart3,
    })
  }

  const roleSpecificItems = {
    ADMIN: [
      {
        title: "User Management",
        url: "/admin/users",
        icon: Users,
      },
        {
          title: "Categories",
          url: "/admin/categories",
          icon: FolderOpen,
        },
        {
          title: "Courses",
          url: "/admin/courses",
          icon: BookOpen,
        },
        {
          title: "School Years",
          url: "/admin/school-years",
          icon: Calendar,
        },
          {
            title: "All Thesis",
            url: "/admin/thesis",
            icon: FileText,
          },
    ],
    PROGRAM_HEAD: [
      {
        title: "Upload Thesis",
        url: "/program-head/upload",
        icon: Upload,
      },
      {
        title: "My Thesis",
        url: "/program-head/thesis",
        icon: FileText,
      },
    ],
    STUDENT: [
      {
        title: "Browse Thesis",
        url: "/thesis/browse",
        icon: BookOpen,
      },
    ],
    TEACHER: [
      {
        title: "Browse Thesis",
        url: "/thesis/browse",
        icon: BookOpen,
      },
    ],
  }

  return [...baseItems, ...(roleSpecificItems[role as keyof typeof roleSpecificItems] || [])]
}

export function AppSidebar({ ...props }: React.ComponentProps<typeof Sidebar>) {
  const { data: session } = useSession()
  const pathname = usePathname()
  const router = useRouter()
  const role = session?.user?.role || "STUDENT"
  const navigationItems = getNavigationItems(role)

  const handleSignOut = async () => {
    try {
      await signOut({ redirect: false })
      router.push("/auth")
    } catch {
      router.push("/auth")
    }
  }

  return (
    <Sidebar {...props}>
      <SidebarHeader>
        <div className="flex items-center justify-between px-2">
          <TeamSwitcher
            teams={[
              { name: "Thesis Archive", logo: BookOpen, plan: role },
            ]}
          />
          <ThemeToggle />
        </div>
      </SidebarHeader>
      <SidebarContent>
        <SidebarGroup>
          <SidebarGroupLabel>Navigation</SidebarGroupLabel>
          <SidebarGroupContent>
            <SidebarMenu>
              {navigationItems.map((item) => {
                const Icon = item.icon
                const isActive = pathname === item.url
                
                return (
                  <SidebarMenuItem key={item.title}>
                    <SidebarMenuButton asChild isActive={isActive}>
                      <Link href={item.url}>
                        <Icon className="mr-2 h-4 w-4" />
                        {item.title}
                      </Link>
                    </SidebarMenuButton>
                  </SidebarMenuItem>
                )
              })}
            </SidebarMenu>
          </SidebarGroupContent>
        </SidebarGroup>
      </SidebarContent>
      <SidebarFooter>
        <NavUser
          user={{
            name: session?.user?.name || "User",
            email: session?.user?.email || "",
            avatar: "", // Will be generated by DiceBear
          }}
        />
      </SidebarFooter>
      <SidebarRail />
    </Sidebar>
  )
}
